version: '3.8'

services:
  # Brew Application Service
  brew-app:
    build: 
      context: ./brew-app
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: kogito-brew-service
    ports:
      - "8081:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      QUARKUS_DATASOURCE_USERNAME: ${POSTGRES_USER:-kogito}
      QUARKUS_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-kogito}
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-kogito}
    depends_on:
      - kafka
      - postgres
    networks:
      - kogito-network

  # Order Application Service
  order-app:
    build:
      context: ./order-app
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: kogito-order-service
    ports:
      - "8082:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      QUARKUS_DATASOURCE_USERNAME: ${POSTGRES_USER:-kogito}
      QUARKUS_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-kogito}
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-kogito}
    depends_on:
      - kafka
      - postgres
    networks:
      - kogito-network

networks:
  kogito-network:
    external: true
