version: '3.8'

services:
  # BAMOE Maven Repository
  bamoe-maven-repo:
    image: quay.io/bamoe/maven-repository:9.2.1-ibm-0005
    container_name: bamoe-maven-repository
    ports:
      - "${MAVEN_REPO_PORT:-9080}:8080"
    networks:
      - kogito-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    container_name: kogito-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-kogito}
      POSTGRES_USER: ${POSTGRES_USER:-kogito}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kogito}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kogito-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kogito -d kogito"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Apache Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: kafka-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
    - "${ZOOKEEPER_PORT:-2181}:2181"
    networks:
      - kogito-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-broker
    depends_on:
      - zookeeper
    ports:
    - "${KAFKA_PORT:-9092}:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kogito-network

  # Brew Application Service
  # brew-app:
  #   build:
  #     context: ./brew-app
  #     dockerfile: src/main/docker/Dockerfile.jvm
  #   container_name: brew-app
  #   ports:
  #     - "8082:8080"
  #   environment:
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  #     JOBS_SERVICE_HOST: localhost
  #     JOBS_SERVICE_PORT: 8082
  #     KOGITO_SERVICE_HOST: localhost
  #     KOGITO_SERVICE_PORT: 8082
  #     INDEX_SERVICE_HOST: localhost
  #     INDEX_SERVICE_PORT: 8082

  #     POSTGRES_HOST: postgres
  #     POSTGRES_PORT: 5432
  #     POSTGRES_DB: kogito
  #     POSTGRES_USER: kogito
  #     POSTGRES_PASSWORD: kogito
  #   depends_on:
  #     - kafka
  #     - postgres
  #   networks:
  #     - kogito-network

  # Order Application Service
  order-app:
    build:
      context: ./order-app
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: order-app
    ports:
      - "8081:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

      JOBS_SERVICE_HOST: localhost
      JOBS_SERVICE_PORT: 8081
      KOGITO_SERVICE_HOST: localhost
      KOGITO_SERVICE_PORT: 8081
      INDEX_SERVICE_HOST: localhost
      INDEX_SERVICE_PORT: 8081

      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: kogito
      POSTGRES_USER: kogito
      POSTGRES_PASSWORD: kogito
    depends_on:
      - kafka
      - postgres
    networks:
      - kogito-network

  # Process management console
  management-console:
    container_name: management-console
    image: quay.io/bamoe/management-console:9.2.1-ibm-0005
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - kogito-network

volumes:
  postgres_data:
    driver: local

networks:
  kogito-network:
    name: kogito-network
    driver: bridge
